# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190326_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
