# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('inprogress', 'In Progress'), ('done', 'Done')], default='Planned', max_length=15),
        ),
    ]
