# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.TextField(),
        ),
    ]
