# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190328_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name_plural': 'Comment Replies'},
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
