# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_forteamform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forteamform',
            name='team',
        ),
        migrations.DeleteModel(
            name='ForTeamForm',
        ),
    ]
