# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-31 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20190329_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Planned', max_length=15),
        ),
    ]
