# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20190331_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
